// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwlbooemozdnhjdveuzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53bGJvb2Vtb3pkbmhqZHZldXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODM5NzUsImV4cCI6MjA3MjY1OTk3NX0.1jqQ2VMyu7-LELWurE2XUEwH78DBs3NgXRpdrGOzPTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});